/**
 * NetwoEligibilityAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CustomerTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENTERPRISE: 'enterprise',

    /**
     * TODO: Write general description for this element
     */
    PROFESSIONAL: 'professional',

};

module.exports = CustomerTypeEnum;
