/**
 * NetwoEligibilityAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EligibilityStatus
 */
class EligibilityStatus extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.errors = this.constructor.getValue(obj.errors);
        this.processing = this.constructor.getValue(obj.processing);
        this.successes = this.constructor.getValue(obj.successes);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'errors', realName: 'errors', array: true, type: 'MError' },
            { name: 'processing', realName: 'processing', array: true },
            { name: 'successes', realName: 'successes', array: true, type: 'Success' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EligibilityStatus;
