/**
 * NetwoEligibilityAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const InterventionTimeGuaranteedApplicabilityEnum = {

    /**
     * TODO: Write general description for this element
     */
    WORKING_DAYS: 'working_days',

    /**
     * TODO: Write general description for this element
     */
    ENUM_7_DAYS: '7_days',

};

module.exports = InterventionTimeGuaranteedApplicabilityEnum;
