/**
 * NetwoEligibilityAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ResolverEnum = {

    /**
     * TODO: Write general description for this element
     */
    BOUYGUES: 'Bouygues',

    /**
     * TODO: Write general description for this element
     */
    COLT: 'Colt',

    /**
     * TODO: Write general description for this element
     */
    LEONIX: 'Leonix',

    /**
     * TODO: Write general description for this element
     */
    ORANGE: 'Orange',

};

module.exports = ResolverEnum;
