/**
 * NetwoEligibilityAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const EligibilityProductResult = require('../lib/Models/EligibilityProductResult');
const EligibilityResult = require('../lib/Models/EligibilityResult');
const EligibilityStatus = require('../lib/Models/EligibilityStatus');
const Entity = require('../lib/Models/Entity');
const Entity1 = require('../lib/Models/Entity1');
const MError = require('../lib/Models/MError');
const Relation = require('../lib/Models/Relation');
const Success = require('../lib/Models/Success');

const classMap = {
    EligibilityProductResult,
    EligibilityResult,
    EligibilityStatus,
    Entity,
    Entity1,
    MError,
    Relation,
    Success,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
